## 00. pyTorch Fundamentals

Resource notebook: https: https://www.learnpytorch.io/00_pytorch_fundamentals/



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


#### Introduction To Tensors

## Creating Tensors

PyTorch tensors are created using torch.Tesor() : https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get scalar back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim 

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural neworks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers-> look at data -> update random numbers`

In [ ]:
#create a random tensor of size/shape (3,4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.9257, 0.8325, 0.1428, 0.6272],
         [0.1662, 0.8005, 0.2269, 0.9403],
         [0.3273, 0.2992, 0.8904, 0.4784]],

        [[0.6242, 0.5944, 0.6965, 0.4187],
         [0.8086, 0.5553, 0.0422, 0.1365],
         [0.0065, 0.2959, 0.5167, 0.2511]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
### Zeros and Ones


In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype #data type

torch.float32

### Creating a Range of Tensors and Tensors-like

In [ ]:
# use torch.arange()
one_to_ten = torch.arange(start = 1, end=11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like( input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,          # what datatype is the tensor (e.g. float32 or float16)
                               device = None,       # cpu, gpu, cuda, what processor(device) the tensor runs on
                               requires_grad=False) # tracking gradients of a tensor while calculating
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)


  1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
  2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
  3. Tensors not on the right deviceto get device from a tensor, can use `tensor.device`


In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4224, 0.0543, 0.5975, 0.5944],
        [0.1647, 0.7337, 0.0838, 0.1741],
        [0.9006, 0.6189, 0.0034, 0.9768]])

In [ ]:
# Find details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4224, 0.0543, 0.5975, 0.5944],
        [0.1647, 0.7337, 0.0838, 0.1741],
        [0.9006, 0.6189, 0.0034, 0.9768]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural neworks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

there are 2 main rule that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
# Element wise multiplication
print(tensor,  "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.44 ms, sys: 1.93 ms, total: 3.37 ms
Wall time: 4.22 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 59 µs, sys: 11 µs, total: 70 µs
Wall time: 75.1 µs


tensor(14)

### One of the most common error in deep learning: Shape errors

In [ ]:
# Shapes matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

to fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

a **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes tensor_A = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")

output = torch.matmul(tensor_A, tensor_B.T)
print("\nOutput:\n")
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean - the torch.mean() function requires a tensor of float datatype to wor
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the postional min and max


In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
torch.argmin(x)

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of target tensor where the maximum value occurs
torch.argmax(x)

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape 
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way


In [ ]:
# create a tensor
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
torch.vstack([x, x, x, x])

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped

x_squeezed = x_reshaped.squeeze()

print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a secific dim (dimension)

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#remove extra dimensions from x_reshaped

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order 
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
#swap the color channels to be the first dimensions
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0][0][0] = 22
x_original[0][0][0], x_permuted[0][0][0]

(tensor(22.), tensor(22.))

## Indexing( selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10). reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [ ]:
# you can also use ":" to select "all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dim but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of the 0dim but only the 1 index val of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dim and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular scienific Python numerical computing library.

becuase of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #.type(torch.float32) # numpy uses float64 by default unless changed
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
# change the value of array, wont change tensor

array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# changing the tensor doesn't change the numpy_tensor
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

 ## Reproducibility (trying to take the random out of random)

In short how a neural nework learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...` 

To reduce the ranomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6740, 0.1841, 0.4710, 0.6713],
        [0.9594, 0.9768, 0.6406, 0.5989],
        [0.0456, 0.7725, 0.3358, 0.2123]])
tensor([[0.1859, 0.6929, 0.4678, 0.3382],
        [0.0174, 0.5864, 0.7003, 0.4702],
        [0.3195, 0.1877, 0.5802, 0.8115]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let's make some random but reproducible tensors
import torch
# Set the random seed
RANDOM_SEED = 42 

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)      #must be recalled every time to get the same rand vals
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Esiest - Use Google Colab for a free GPU (options to upgrade as well)
2. use your own GPU - takes a bit of setup and requires the investment of perchasing a GPU
3. use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

for 2, 3 PyTorch + GPU drivers (CUDA takes a bit of set up, to do this refer to PyTorch documentation

In [ ]:
!nvidia-smi

Mon Dec 19 16:49:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P0    27W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 2. Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

For PyTorch since it's capabl of running compute on the GPU or CPU, it's best practice to setup device agnostic code:

https://pytorch.org/docs/stable/notes/cuda.html#cuda-semantics

e.g run on GPU if available, else default to CPU

In [ ]:
# setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/ models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# if the tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# must first set tensor to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum

In [ ]:
import torch
# 2. create random tensor with shape (7, 7)
random_tensor_A = torch.rand(7, 7)
random_tensor_A

tensor([[0.1464, 0.8776, 0.3817, 0.8343, 0.4181, 0.3884, 0.0757],
        [0.9850, 0.7370, 0.5824, 0.6527, 0.7701, 0.4466, 0.6014],
        [0.4703, 0.0626, 0.9565, 0.4511, 0.5856, 0.3090, 0.9751],
        [0.7819, 0.8518, 0.5797, 0.4328, 0.2795, 0.4299, 0.6232],
        [0.1929, 0.9083, 0.8734, 0.2718, 0.4595, 0.7327, 0.9029],
        [0.8570, 0.3185, 0.6136, 0.5848, 0.5592, 0.2724, 0.1474],
        [0.7441, 0.1819, 0.3846, 0.0324, 0.3367, 0.1122, 0.4549]])

In [ ]:
# 3. multiply random_tensor_A with a tensor of size (1, 7)
random_tensor_B = torch.rand(1, 7)
random_tensor_A * random_tensor_B.T

tensor([[0.0182, 0.1091, 0.0474, 0.1037, 0.0520, 0.0483, 0.0094],
        [0.4625, 0.3461, 0.2735, 0.3065, 0.3616, 0.2097, 0.2824],
        [0.1937, 0.0258, 0.3940, 0.1858, 0.2412, 0.1273, 0.4016],
        [0.6726, 0.7327, 0.4986, 0.3722, 0.2404, 0.3698, 0.5360],
        [0.0836, 0.3934, 0.3783, 0.1177, 0.1990, 0.3174, 0.3911],
        [0.3173, 0.1179, 0.2272, 0.2165, 0.2070, 0.1008, 0.0546],
        [0.0649, 0.0159, 0.0335, 0.0028, 0.0293, 0.0098, 0.0396]])

In [ ]:
# 4. set random seed and do previous exercises again
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(7, 7)
random_tensor_B = torch.rand(1, 7)
random_tensor_A.matmul(random_tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
# 5. set gpu seed to 1234
torch.cuda.manual_seed(1234)

In [ ]:
# 6. create 2 tensors of size 2,3 and send both to gpu
torch.manual_seed(1234)
device = "cuda"

random_tensor_C = torch.rand(2, 3)
random_tensor_C = random_tensor_C.to(device)

random_tensor_D = torch.rand(2, 3)
random_tensor_D = random_tensor_D.to(device)
random_tensor_C.shape, random_tensor_D.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [ ]:
# 7. perform matrix multiplication on the tensors made in 6
multiplied_tensor =  random_tensor_C.matmul(random_tensor_D.T)
multiplied_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [ ]:
# find min and max
multiplied_tensor.min(), multiplied_tensor.max()

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

In [ ]:
# find min and max indeces
multiplied_tensor.argmin(), multiplied_tensor.argmax()

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [ ]:
# make a random tensor with shape (1, 1, 1, 10) and get a tensor with shape (10). set sed to 7 and print both tensors and their shapes
torch.manual_seed(7)
rand_tensor = torch.rand(1, 1, 1, 10)
squeezed_tensor = torch.squeeze(rand_tensor)

print(f"old tensor: {rand_tensor}")
print(f"old tensor shape: {rand_tensor.shape}")
print(f"\n new tensor: {squeezed_tensor}")
print(f"new tensor shape: {squeezed_tensor.shape}")

old tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
old tensor shape: torch.Size([1, 1, 1, 10])

 new tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
new tensor shape: torch.Size([10])
